---

- name: Install the latest version of Tor and torsocks [RedHat Based]
  yum:
    name: ['tor', 'torsocks']
    update_cache: true
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install the latest version of Tor and torsocks [Debian Based]
  apt:
    name: ['tor', 'torsocks']
    update_cache: true
    state: present
  when: ansible_os_family == 'Debian'
