---

- name: Update sources
  apt: update_cache=yes cache_valid_time=86400
  changed_when: no
  when: ansible_os_family == 'Debian'

- name: Install tor and torsocks
  package:
    name: ['tor', 'torsocks']
    state: present
    default_release: "{{ tor_default_release|default(omit) }}"
