---

- name: Update sources
  apt: update_cache=yes cache_valid_time=86400
  changed_when: no
  when: ansible_os_family == 'Debian'

- name: Install the latest version of Tor and torsocks [RedHat Based]
    dnf:
      name: ['tor', 'torsocks']
      state: latest
    #register: tor_package
    when: ansible_os_family == 'RedHat'


  - name: Install the latest version of Tor and torsocks [Debian Based]
    apt:
      name: ['tor', 'torsocks']
      update_cache: true
      state: present
    #register: tor_package
    when: ansible_os_family == 'Debian'

